---
title: "Poblacion"
output: html_document
---

**Estás viendo la población simulada**. Al hacer un inventario, no conocemos la población, no sabemos cuantos individuos hay ni cuales son los valores de sus alturas y diámetros. Esto implica que en aplicaciones reales no conoceremos los valores de los parámetros de interés que querremos estimar.

Sin embargo, las simulaciones son útiles para acercarnos al problema del muestreo, conocemos todos los individuos en el área a maestrear (cuadrado rojo), y podemos calcular todos los parámetros de interés para posteriormente analizar distintas configuraciones del muestreo.

En este caso hemos considerado los siguientes parámetros de interés:

-   Total de individuos

$$Total\:individuos= \sum_{i=1}^{\cal{N}}1$$ - Total secciones normales

$$Total\:secciones\:normales=\sum_{i=1}^{\cal{N}}g_i=\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2$$

-   Densidad (pies por ha)

$$N=\frac{1}{A}\sum_{i=1}^{\cal{N}}1$$

-   Total secciones normales

$$G=\frac{1}{A}\sum_{i=1}^{\cal{N}}g_i=\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2$$

-   Diámetro cuadrático medio

$$dg=\sqrt(\frac{G}{N}\frac{4}{\pi})=\sqrt(\frac{\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i^2}{\frac{1}{A}\sum_{i=1}^{\cal{N}}1}\frac{4}{\pi})$$

-   Altura media

$$\bar{h}=\frac{\sum_{i=1}^{\cal{N}}h_i}{\sum_{i=1}^{\cal{N}}1}$$

-   Altura dominante

$$h_o =\sum_{i=1}^{\cal{N}}g_i=\sum_{i=1}^{\cal{N}}\frac{\pi}{4}dn_i²$$
